name: Build and Deploy to S3

on:
  # mainブランチへのプッシュをトリガーにする
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main  # リポジトリをチェックアウト  

      - name: Install Dependencies
        run: npm install
      # ビルドしてdistディレクトリ以下のファイルを更新
      - name: Build
        run: npm run build 

      - name: Deploy  # S3にデプロイ 
        env:
          # IAMユーザーに作成したアクセスキー
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: | # S3のバケットにデプロイ
          aws s3 sync --region ap-northeast-1 ./dist s3://nuxt-app-20240218 --delete
          aws s3 cp --recursive --region ap-northeast-1 ./dist s3://nuxt-app-20240218
      